version: "3.9"

networks:
  laravel:
  reactjs:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    ports: 
      - "8088:80"
    volumes:
      - ../pbl5-backend:/var/www/html
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql
    container_name: database
    restart: unless-stopped
    tty: true
    ports: 
      - "4306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: DemoDB
      MYSQL_USER: DemoDB
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: DockerFile.BE
    container_name: php
    restart: always
    volumes:
      - ../pbl5-backend:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel

  frontend:
    build: 
      context: ../pbl5-frontend
      dockerfile: DockerFile.dev
    command: npm run start
    container_name: web
    ports:
      - "3000:3000"        
    volumes: 
      - ../pbl5-frontend:/frontend
      - /frontend/node_modules
    networks:
      - reactjs
